services:
  postgres:
    image: "postgres:latest"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web-development:
    build: 
      dockerfile: Dockerfile
    ports:
      - 80:3000
    env_file: .env
    environment:
      # hardcode link to the compose postgres service
      - DB_URL=postgres://postgres:password@postgres:5432/postgres
    depends_on:
      postgres:
        condition: service_healthy

